### ISSUE TITLE
怎么用

### ISSUE THREAD

**Issue by characte1** [lryong/tutorials-from-runoob#1]
我不会任何Python，所以爬虫该怎么用，能教一下吗？

**Comment by lryong** [comment]
需要在终端下执行以下命令：
```python
git clone https://github.com/lryong/tutorials-from-runoob
cd tutorials-from-runoob
pip install -r requirements.txt
python download_tutorials.py // 会在当前目录下载教程,css样式文件在Runoob教程/runoob目录
```

这个爬虫的初衷是自己学python2.7的时候写的一个小demo， 只爬runoob上的数据。

如果你想学python, 推荐[Fluent Python ](https://evanli.github.io/programming-book-3/Python/Fluent%20Python.pdf)
